sudo: false

os:
  - linux
  - osx
  - windows

language: generic

cache:
  timeout: 1000
  directories:
    - $HOME/.stack/
    - $HOME/.local/bin/
    - .stack-work/

branches:
  only:
    - master

install:
  - set -e
  - source ./.travis.${TRAVIS_OS_NAME}.env
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - if [[ ! -x ~/.local/bin/stack ]]; then travis_retry curl -L ${STACK_URL} | ${UNPACK_CMD} ~/.local/bin '*/stack'; chmod a+x ~/.local/bin/stack; fi
  - which stack
  - type -a stack
  - stack --version
  - echo ~
  - ~/.local/bin/stack --version
  - stack setup
  - stack exec -- ghc --version
  - if [[ ! -x ~/.local/bin/shelltest ]]; then stack install shelltestrunner-1.9; fi
  - shelltest --version

script:
  - stack test
  - stack build --ghc-options -O2 # build artifact with optimizations

before_deploy:
  - mv "$(stack path --local-install-root)/bin/ion-fmt-exe" "$(stack path --local-install-root)/bin/ion-fmt-${TRAVIS_OS_NAME}"

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: "$(stack path --local-install-root)/bin/ion-fmt-${TRAVIS_OS_NAME}"
    skip_cleanup: true
    on:
      branch: master
      tags: true
