name:                ion-fmt
version:             0.1.0.0
github:              "luke-biel/ion-fmt"
license:             MIT
author:              "Łukasz Biel"
maintainer:          "lukasz.p.biel@gmail.com"
copyright:           "2020 Łukasz Biel"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Github username here/ion-fmt#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - split >= 0.2 && < 0.3

executables:
  ion-fmt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ion-fmt
    - optparse-applicative >= 0.14 && < 0.15
    - text >= 1.2 && < 1.3

tests:
  ion-fmt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ion-fmt
    - hspec >= 2.7 && < 2.8
